routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ParkingRecordController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\GuestController;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('guest', [GuestController::class, 'index'])->name('guest.index');

Route::get('ajax/getSlot', [ParkingRecordController::class, 'getSlot'])->name('guests.slot');

Route::middleware('guest')->group(function() {
    Route::prefix('/login')->group(function() {
        Route::get('/', [AuthController::class, 'login'])->name('login.index');
        Route::post('/', [AuthController::class, 'storeLogin'])->name('login.store');
    });
});

Route::middleware('auth')->group(function(){
    Route::get('/', [HomeController::class, 'index'])->name('dashboard');
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::prefix('user')->group(function(){
        Route::get('/', [UserController::class, 'index'])->name('user.index')->can('user');
        Route::post('/bulk/{type}', [UserController::class, 'bulkAction'])->name('user.bulk')->where('type','delete')->can('user');
        Route::post('/{id}/delete', [UserController::class, 'delete'])->name('user.destroy')->can('user');
        Route::post('/{id}/update', [UserController::class, 'update'])->name('user.update')->can('user');
        Route::get('/{id}/edit', [UserController::class, 'edit'])->name('user.edit')->can('user');
        Route::post('/store', [UserController::class, 'store'])->name('user.store')->can('user');
        Route::get('/create', [UserController::class, 'create'])->name('user.create')->can('user');
    });

    Route::prefix('role')->group(function(){
        Route::get('/', [UserRoleController::class, 'index'])->name('role.index')->can('role');
        Route::post('/{id}/delete', [UserRoleController::class, 'delete'])->name('role.destroy')->can('role');
        Route::post('/{id}/update', [UserRoleController::class, 'update'])->name('role.update')->can('role');
        Route::get('/{id}/edit', [UserRoleController::class, 'edit'])->name('role.edit')->can('role');
        Route::post('/store', [UserRoleController::class, 'store'])->name('role.store')->can('role');
        Route::get('/create', [UserRoleController::class, 'create'])->name('role.create')->can('role');
    });

    Route::prefix('parking')->group(function(){
        Route::get('/', [ParkingRecordController::class, 'index'])->name('parking.index')->can('parking');
        Route::get('/{mode}', [ParkingRecordController::class, 'indexMode'])->name('parking.mode')->where('type','checkin|checkout')->can('parking');
        Route::get('/{mode}/{type}', [ParkingRecordController::class, 'indexType'])->name('parking.type')->where('type','r2|r4')->can('parking');
        Route::post('/{type}/checkin', [ParkingRecordController::class, 'storeCheckin'])->name('parking.checkin')->where('type','r2|r4')->can('parking');
        Route::post('/{type}/checkout', [ParkingRecordController::class, 'storeCheckout'])->name('parking.checkout')->where('type','r2|r4')->can('parking');
    });

    Route::prefix('settings')->group(function(){
        Route::get('/', [SettingController::class, 'index'])->name('settings.index')->can('settings');
        Route::post('/update', [SettingController::class, 'update'])->name('settings.update')->can('save.settings');
    });

    Route::prefix('notifications')->group(function(){
        Route::get('/', [NotificationController::class, 'index'])->name('notif.index');
        Route::post('push', [NotificationController::class, 'store'])->name('notif.store');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use NotificationChannels\WebPush\HasPushSubscriptions;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasPushSubscriptions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(UserRole::class, 'user_role_id');
    }

    public function hasAccess($access) : bool
    {
        foreach ($this->role->permissions as $list) {
            if ($list->slug == $access) {
                return true;
            }
        }

        return false;
    }

    public function getMapsUrlAttribute($value)
    {
        // https://www.google.com/maps/search/?api=1&query=-7.7857304,110.3666397
        return "https://www.google.com/maps/search/?api=1&query=".$this->lat.",".$this->long;
    }

    public function subscribe()
    {
        return $this->hasOne(PushSubscribe::class, 'subscribable_id');
    }
}

app/Http/Controllers/UserController.php
<?php
namespace App\Http\Controllers;


use App\Services\UserRoleService;
use App\Services\UserService;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Password;

class UserController extends Controller
{
    protected $service;

    function __construct(UserService $service)
    {
        $this->service = $service;
    }

    public function index(Request $request)
    {
        $this->pageComponents($request);

        $this->data['data'] = $this->service->getPaginate($request);

        if ($request->ajax()) {
            return response()->json([
                'html' => view('user._table', $this->data)->render()
            ]);
        }

        return view('user.index', $this->data);
    }

    public function create(UserRoleService $userRoleService)
    {
        $this->data['roles'] = $userRoleService->getDropdown();

        return view('user.create', $this->data);
    }

    public function store(Request $request)
    {
        $request->validate([
            'role'      => 'required',
            'name'      => 'required',
            'email'     => 'required|email|unique:users,email',
            'password'  => 'required|confirmed|min:6',
        ]);

        try {
            $this->service->insert($request);

            return response()->json(['redirect'=>route('user.index')]);
        } catch (\Throwable $th) {
            return response()->json(['error' => $th->getMessage()]);
        }
    }

    public function edit(Request $request, UserRoleService $userRoleService)
    {
        try {
            $this->data['data'] = $this->service->getById($request->id);

            if(!$this->data['data']) {
                throw new Exception('No data');
            }

            $this->data['roles'] = $userRoleService->getDropdown();

            return view('user.edit', $this->data);
        } catch (\Throwable $th) {
            return redirect()->route('user.index');
        }
    }

    public function update(Request $request)
    {
        $rules = [
            'role'      => 'required',
            'name'      => 'required',
            'email'     => [
                'required','email',
                Rule::unique('users')->ignore($request->id)
            ]
        ];
        if ($request->password) {
            $rules['password'] = 'confirmed|min:6';
        }
        $request->validate($rules);

        try {
            $this->service->update($request);

            return response()->json(['redirect'=>route('user.index')]);
        } catch (\Throwable $th) {
            return response()->json(['error' => $th->getMessage()]);
        }
    }

}

resources/views/user/_table.blade.php
<div class="table-responsive">
    <table class="table align-middle">
        <thead>
        <tr>
        <th class="check">
            <input class="form-check-input check-all" type="checkbox">
        </th>
        <th>Staff Name</th>
        <th>Email</th>
        <th>Status</th>
        <th>Location</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        @forelse ($data as $item)
            <tr>
                <td class="check"><input class="form-check-input check-row" name="ids[]" type="checkbox" value="{{$item->id}}"></td>
                <td>{{$item->name}}</td>
                <td>{{$item->email}}</td>
                <td>
                    @if ($item->is_active==1)
                    <span class="badge text-bg-success">Active</span>
                    @else
                    <span class="badge text-bg-danger">Inactive</span>
                    @endif
                </td>
                <td>
                    @if ($item->lat && $item->long)
                    <a href="{{ $item->maps_url }}" target="_blank">Check Location</a>
                    @else
                    -
                    @endif
                </td>
                <td class="table-action">
                    <div class="btn-group dropstart">
                        <a class="btn btn-sm dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fi fi-rr-menu-dots-vertical"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ route("user.edit", ["id"=>$item->id]) }}">Edit</a></li>
                            <li><a class="dropdown-item text-danger" href="#">Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        @empty
        @include('_partial.table-nodata', ['colspan' => 5])
        @endforelse
    </tbody>
</table>
</div>
<div class="table-footer">
    <div class="row">
        <div class="col-auto">
            <span class="table-count">Total Staff: {{$data->total()}}</span>
        </div>
        <div class="col-auto">
            <div class="d-flex flex-column flex-md-row">
                {{$data->links()}}
                @include('_partial.table-entries')
            </div>
        </div>
    </div>
</div>

resources/views/user/create.blade.php
@extends('layout')

@section('content')
<div class="page-title">
    <h3 class="mb-0">User</h3>
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="#">User</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add New</li>
    </ol>
</div>

<div class="page-content">
    <form method="POST" action="{{ route('user.store') }}">
        @csrf
        <div class="row row-wrapper">
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="mb-3">
                            <label for="role" class="form-label">Role</label>
                            <select class="form-select select2" name="role" data-placeholder="Select here" data-allow-clear="false">
                                <option value=""></option>
                                @foreach ($roles as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="name" class="form-label">Staff Name</label>
                            <input type="text" name="name" id="name" class="form-control" placeholder="Enter text here ...">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" name="email" id="email" class="form-control" placeholder="Enter text here ...">
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" name="password" id="password" class="form-control" placeholder="Enter text here ...">
                        </div>
                        <div class="mb-3">
                            <label for="password_confirmation" class="form-label">Re-type Password</label>
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="Enter text here ...">
                        </div>
                        <div class="mb-3">
                            <label for="status" class="form-label">Status</label>
                            <div>
                                <div class="toggle-btn">
                                    <input class="form-check-input" type="checkbox" role="switch" id="status" name="status" value="1">
                                    <label for="status" data-off="Inactive" data-on="Active"></label>
                                </div>
                            </div>
                        </div>

                        <div class="row d-flex justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-light me-2" href="{{ route('user.index') }}">Cancel</a>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layout')

@section('content')
<div class="page-title">
    <h3 class="mb-0">User</h3>
    <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="#">User</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add New</li>
    </ol>
</div>

<div class="page-content">
    <form method="POST" action="{{ route('user.update', ['id'=>$data->id]) }}">
        @csrf
        <div class="row row-wrapper">
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="mb-3">
                            <label for="role" class="form-label">Role</label>
                            <select class="form-select select2" name="role" data-placeholder="Select here" data-allow-clear="false">
                                <option value=""></option>
                                @foreach ($roles as $item)
                                @if ($item->id == $data->user_role_id)
                                <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                @else
                                <option value="{{$item->id}}">{{$item->name}}</option>
                                @endif
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="name" class="form-label">User Name</label>
                            <input type="text" name="name" id="name" class="form-control" placeholder="Enter text here ..." value="{{$data->name}}">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" name="email" id="email" class="form-control" placeholder="Enter text here ..." value="{{$data->email}}">
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" name="password" id="password" class="form-control" placeholder="Enter text here ...">
                        </div>
                        <div class="mb-3">
                            <label for="password_confirmation" class="form-label">Re-type Password</label>
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="Enter text here ...">
                        </div>
                        <div class="mb-3">
                            <label for="status" class="form-label">Status</label>
                            <div>
                                <div class="toggle-btn">
                                    <input class="form-check-input" type="checkbox" role="switch" id="status" name="status" value="1" {{ $data->is_active?'checked':'' }}>
                                    <label for="status" data-off="Inactive" data-on="Active"></label>
                                </div>
                            </div>
                        </div>

                        <div class="row d-flex justify-content-end">
                            <div class="col-auto">
                                <a class="btn btn-light me-2" href="{{ route('user.index') }}">Cancel</a>
                                <button class="btn btn-primary" type="submit">Save</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layout')

@section('content')
<div class="page-title">
    <div class="row d-flex justify-content-between align-items-center">
        <div class="col">
            <h3 class="mb-0">User Management</h3>
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="#">User</a></li>
                <li class="breadcrumb-item active" aria-current="page">List</li>
            </ol>
        </div>
        <div class="col-auto">
            <a class="btn btn-primary" href="{{ route('user.create') }}">Add new</a>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="card">
        <div class="card-body">
            <div class="table-header">
                <div class="row">
                    <div class="col-12 col-md-auto bulk-action">
                        <div class="row g-2">
                            <div class="col-auto">
                                <select class="form-select form-select-sm select2-infinity" aria-label="Bulk action" disabled data-placeholder="Bulk action" data-width="150">
                                    <option value=""></option>
                                    <option value="delete" data-action="{{route('user.bulk',['type'=>'delete'])}}">Delete</option>
                                </select>
                            </div>
                            <div class="col-auto">
                                <button type="button" class="btn btn-primary btn-sm --btn-bulk" disabled>Submit <span class="checked-count badge text-bg-secondary">0</span></button>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="mb-3">
                            <form action="{{route('user.index')}}" id="form-filter">
                                @csrf
                                <div class="row g-2 align-items-center">
                                    <div class="col-12 col-md-auto">
                                      <input type="text" name="search" id="search-data" class="form-control form-control-sm" placeholder="Search data here ...">
                                    </div>
                                    <div class="col-auto">
                                        <button type="submit" class="btn btn-primary btn-sm">Apply</button>
                                    </div>
                                  </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-auto">
                        @include('_partial.table-entries')
                    </div>
                </div>
            </div>
            <div id="dataTable">
                @include('user._table')
            </div>
        </div>
    </div>
</div>
@endsection